sudo java -classpath "./bin\
:./lib/webgraph/webgraph-3.4.2.jar\
:./lib/webgraph/dsiutils-2.2.2.jar\
:./lib/webgraph/fastutil-6.6.1.jar\
:./lib/webgraph/mg4j-big-4.0.4.jar\
:./lib/webgraph/sux4j-3.2.1.jar\
:./lib/webgraph/mg4j-4.0.3.jar\
:./lib/webgraph/webgraph-big-3.3.5.jar\
:./lib/webgraph/webgraph-deps/collections-generic-4.01.jar\
:./lib/webgraph/webgraph-deps/dsiutils-2.2.2.jar\
:./lib/webgraph/webgraph-deps/logback-classic-1.1.2.jar\
:./lib/webgraph/webgraph-deps/colt-1.2.0.jar\
:./lib/webgraph/webgraph-deps/fastutil-6.5.15.jar\
:./lib/webgraph/webgraph-deps/logback-core-1.1.2.jar\
:./lib/webgraph/webgraph-deps/commons-collections-20040616.jar\
:./lib/webgraph/webgraph-deps/guava-18.0.jar\
:./lib/webgraph/webgraph-deps/slf4j-api-1.7.7.jar\
:./lib/webgraph/webgraph-deps/commons-configuration-1.8.jar\
:./lib/webgraph/webgraph-deps/jsap-2.1.jar\
:./lib/webgraph/webgraph-deps/stax-api-1.0.1.jar\
:./lib/webgraph/webgraph-deps/commons-io-2.4.jar\
:./lib/webgraph/webgraph-deps/jung-algorithms-2.0.1.jar\
:./lib/webgraph/webgraph-deps/sux4j-3.0.10.jar\
:./lib/webgraph/webgraph-deps/commons-lang-2.6.jar\
:./lib/webgraph/webgraph-deps/commons-lang3-3.3.2.jar\
:./lib/webgraph/webgraph-deps/commons-logging-1.1.1.jar\
:./lib/webgraph/webgraph-deps/jung-api-2.0.1.jar\
:./lib/webgraph/webgraph-deps/webgraph-3.3.0.jar\
:./lib/webgraph/webgraph-deps/commons-math3-3.3.jar\
:./lib/webgraph/webgraph-deps/jung-io-2.0.1.jar\
:./lib/webgraph/webgraph-deps/wstx-asl-3.2.6.jar\
:./lib/webgraph/webgraph-deps/concurrent-1.3.4.jar\
:./lib/webgraph/webgraph-deps/log4j-over-slf4j-1.7.5.jar\
" txt.TestGeneral ./example_dataset/enron/enron ./example_dataset/enron.txt
